// Better Auth route handlers. The sign-in / callback / session endpoints are
// generated by Better Auth and re-exported here as the App Router GET/POST
// handlers. The catch-all segment is `[...all]` (Better Auth's convention),
// renamed from Auth.js's `[...nextauth]`; the handler is `toNextJsHandler`.

import { auth } from "@/lib/auth";
import { toNextJsHandler } from "better-auth/next-js";

export const { GET, POST } = toNextJsHandler(auth.handler);
