// Auth.js v5 route handlers for the host-shell. The OIDC sign-in / callback /
// session endpoints are generated by NextAuth and re-exported here as the App
// Router GET/POST handlers.

import { handlers } from "@/auth";

export const { GET, POST } = handlers;
